services:
  - type: web
    name: events
    env: node
    plan: free
    buildCommand: cd server && npm install --legacy-peer-deps
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://dafitech:your_password@cluster0.mongodb.net/dafitech?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: FRONTEND_URL
        value: https://www.dafitech.org
