services:
  # Backend API Service
  - type: web
    name: dafitech-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run render-build
    startCommand: npm run render-start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://dafitech:your_password@cluster0.mongodb.net/dafitech?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: FRONTEND_URL
        value: https://www.dafitech.org

