services:
  - type: web
    name: dafitech-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

