services:
  - type: web
    name: dafitech-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run render-build
    startCommand: npm run render-start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

